### PR TITLE
Dev adam

### PR DESCRIPTION
**Pull request by Adam746**

### CODE REVIEW

**Comment by Adam746** [comment]
Only the last three commits are new.  Everything prior is from demo_Build branch

**Comment by Adam746** [comment]
Actually the second to last is just a merge commit with demo_Build

**Review by KadeWern — APPROVED** [review]
Nice color changes. Also, I noticed a few changes up top that seem like they're just refactors of methods. They all look similar to what's on my branch as well - demo methods. All looks well.

**Comment by KadeWern** [comment]
Let me know once everyone has reviewed and you're ready to merge.

**Pull request merged**
